KsiazkaOnline/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace KsiazkaOnline.Models
{
    public class Recipe
    {
        [Key]
        [Required]
        public int ID { get; set; }

        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public double Score { get; set; }
        public RecipeType RecipeType { get; set; }

        [Display(Name = "Rodzaj potrawy")]
        public int RecipeTypeId { get; set; }

      

        //public Recipe()
        //{
        //    Random rd = new Random();
        //    Score = rd.NextDouble()*5;

        //}


    }
}

KsiazkaOnline/Models/RecipeType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KsiazkaOnline.Models
{
    public class RecipeType
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

KsiazkaOnline/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using KsiazkaOnline.Models;
using KsiazkaOnline.ViewModels;

namespace KsiazkaKucharska.Controllers
{
    public class RecipesController : Controller
    {
        Random rnd = new Random();
        private ApplicationDbContext _context;
        static public RecipeWithReview tempModel;

        public RecipesController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Random()
        {
            //var recipe1 = new Recipe() {RecipeId=1, Title = "Burger", Description = "Podgrzej go napatelni a pozniej pomieszaj"};
            //var User = new User();
            //var randomRecipeViewModel = new RandomRecipeViewModel(){ recipe=recipe1, users=new List<User>() };

            var random = rnd.Next(0, _context.Recipes.Count());
            var recipe = _context.Recipes.ToList().ElementAt(random);
            var recipeTypes = _context.RecipesTypes.ToList();
            var reviews = _context.Reviews.Where(r => r.RecipeId == recipe.ID).ToList();

            var model = new RecipeWithReview { recipe = recipe, reviews = reviews, types = recipeTypes };
            tempModel = model;
            return View("Details", model);
        }



        public ActionResult Index(int? pageIndex, string sortBy)
        {
            if (!pageIndex.HasValue)
            {
                pageIndex = 1;
            }

            if (String.IsNullOrWhiteSpace(sortBy))
            {
                sortBy = "Name";
            }

            return Content($"Page Index : {pageIndex} & SortBy: {sortBy}");
        }


        [Route("recipes/released/{year}/{month:regex(\\d{2}):range(1,12)}")]
        public ActionResult ByReleaseDate(int year, int month)
        {

            return Content(year + "/" + month);
        }

        [Authorize]
        public ActionResult List()
        {

            var recipes = _context.Recipes.ToList();
            var types = _context.RecipesTypes.ToList();



            recipes.Where(p => p.Score > 3);

            if (recipes == null)
                return HttpNotFound();


            var recipeWithTypeModel = new RecipeWithTypeViewModel() { recipes = recipes, types = types };

            return View(recipeWithTypeModel);
        }


        public ActionResult Details(int id)
        {
            var recipe = _context.Recipes.SingleOrDefault(c => c.ID == id);
            var recipeTypes = _context.RecipesTypes.ToList();
            var reviews = _context.Reviews.Where(r => r.RecipeId == id).ToList();

            var model = new RecipeWithReview { recipe = recipe, reviews = reviews, types = recipeTypes };
            if (recipe == null)
                return HttpNotFound();

            tempModel = model;
            return View(model);
        }

        public ActionResult New()
        {
            var types = _context.RecipesTypes.ToList();
            var recipeWithType = new NewRecipeViewModel() { types = types };
            return View(recipeWithType);
        }

        [HttpPost]
        public ActionResult Save(Recipe recipe)
        {
            if (!ModelState.IsValid)
            {
                var model = new NewRecipeViewModel() { recipe = recipe, types = _context.RecipesTypes.ToList() };
                return View("New", model);
            }

            if (recipe.ID == 0)
            {
                _context.Recipes.Add(recipe);
            }
            else
            {
                var tempRecipe = _context.Recipes.SingleOrDefault(r => r.ID == recipe.ID);
                tempRecipe.Title = recipe.Title;
                tempRecipe.Description = recipe.Description;
                tempRecipe.RecipeTypeId = recipe.RecipeTypeId;

            }

            _context.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var recipe = _context.Recipes.SingleOrDefault(r => r.ID == id);
            if (recipe == null)
                return HttpNotFound();

            var model = new NewRecipeViewModel { recipe = recipe, types = _context.RecipesTypes.ToList() };


            _context.SaveChanges();
            return View("New", model);
        }

        public ActionResult Delete(int id)
        {
            _context.Recipes.Where(r => r.ID == id).First();
            _context.Recipes.Remove(_context.Recipes.Find(id));
            _context.SaveChanges();
            var model = new RecipeWithTypeViewModel { recipes = _context.Recipes.ToList(), types = _context.RecipesTypes.ToList() };

            return View("List", model);
        }

        public ActionResult Search(RecipeWithTypeViewModel recipeViewModel)
        {
            //    _context.Recipes.Where(r => r.ID == id).First();
            //    _context.Recipes.Remove(_context.Recipes.Find(id));
            //    _context.SaveChanges();
            List<Recipe> searchedRecipes = _context.Recipes.Where(r => r.Title.Contains(recipeViewModel.searchPhrase)).ToList();
            var model = new RecipeWithTypeViewModel { recipes = searchedRecipes, types = _context.RecipesTypes.ToList() };

            return View("List", model);
        }


        //public ActionResult DeleteReview(int id)
        //{
        //    _context.Reviews.Where(r => r.ReviewId == id).First();
        //    _context.Reviews.Remove(_context.Reviews.Find(id));
        //    _context.SaveChanges();
        //    var model = new RecipeWithTypeViewModel { recipes = _context.Recipes.ToList(), types = _context.RecipesTypes.ToList() };
        //    return View("Details", model);
        //}

    }


}

KsiazkaOnline/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KsiazkaOnline.ViewModels;
using KsiazkaKucharska.Controllers;
using KsiazkaOnline.Models;

namespace AplikacjaWebowa.Controllers
{
    public class ReviewsController : Controller
    {


        private ApplicationDbContext _context;

        public ReviewsController()
        {
            _context = new ApplicationDbContext();
        }


        [HttpPost]
        public ActionResult Save(RecipeWithReview recipeWithReview)
        {
            if (!ModelState.IsValid)
            {
                //return Content("");
            }
            var id = RecipesController.tempModel.recipe.ID;

            // recipeWithReview.review.ReviewId = recipeWithReview.recipe.ID;
            
            recipeWithReview.review.SetId(id);
            recipeWithReview.review.PublishDate = DateTime.Now;
            recipeWithReview.review.SetEmail(User.Identity.Name);
            _context.Reviews.Add(recipeWithReview.review);
            _context.SaveChanges();


            var model = new RecipeWithReview { recipe = _context.Recipes.SingleOrDefault(r => r.ID == id), reviews = _context.Reviews.Where(r => r.RecipeId == id).ToList(), types = _context.RecipesTypes.ToList() };
            

            // return RedirectToAction("List", "Recipes");
            //return Content("Pomyślne logowanie");
            return RedirectToAction("Details",
            "Recipes", new { id = id });
            // RedirectToAction("actionName", "controllerName", new {/* routeValues, for example: */ id = 5 });


        }




    }
}

KsiazkaOnline/Views/Recipes/Details.cshtml
@model KsiazkaOnline.ViewModels.RecipeWithReview
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="recipeDetailContainer">
<div id="recipeTitle">@Model.recipe.Title</div>
<div id="recipeDescription">@Model.recipe.Description</div>
</div>

<div class="CommentSection">
    <font size="6">Komentarze :</font>


    @foreach (var review in Model.reviews)
    {
        <div class="SingleComment">
            @review.Text
            <div class="CommentPublishDate">@review.PublishDate</div>
            <div class="CommentAuthor">
               
                
                @review.Email
                
            </div>
        </div>
    }

    @if (User.Identity.IsAuthenticated)
    {
        using (Html.BeginForm("Save", "Reviews"))
        {


            <div class="form-group">

                <label>Dodaj swój komentarz :</label>
                @Html.TextBoxFor(r => r.review.Text, new { @class = "form-control" })
            </div>

            @Html.HiddenFor(r => r.review.ApplicationUser)
            <button type="submit" , class="btn btn-primary">Dodaj</button>

        }

    }
</div>
    
    

KsiazkaOnline/Views/Recipes/List.cshtml
@using KsiazkaOnline.Models
@model KsiazkaOnline.ViewModels.RecipeWithTypeViewModel

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Search", "Recipes"))
{<br /><br />
    <table>
        <thread>
            <tr>
                <td>
                    <div class="form-group">
                        <h5>
                        <h4><b>Wyszukaj przepisu</b></h4>
                        @Html.TextBoxFor(r => r.searchPhrase, "SearchPhrase", new { @class = "form-control" })
                         </h5>
                    </div>
                </td>
                <td>


                    <div>
                        <br/>
                        <button type="submit" , class="btn btn-primary">Szukaj</button>
                    </div>
                </td>
            </tr>
        </thread>
    </table>
}

@if (!Model.recipes.Any())
{
    <p>Brak przepisów.</p>
    <p>
        @Html.ActionLink("Dodaj przepis", "New", "Recipes", null, new { @class = "btn btn-primary" })
    </p>
}


else
{
    @*<table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Przepis</th>
                <th>Rodzaj</th>
                <th>Wynik</th>
                <th>Sprawdz</th>
                <th>Usun</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var recipe in Model.recipes)
            {
                <tr>
                    <td>@Html.ActionLink(recipe.Title, "Edit", "Recipes", new { id = recipe.ID }, null)</td>
                    <td>@recipe.RecipeType.Name</td>
                    <td>@recipe.Score/5</td>
                    <td>
                        @Html.ActionLink("Przepis", $"Details/{recipe.ID}", "Recipes", null, new { @class = "btn btn-primary" })
                    </td>
                    <td>
                        @Html.ActionLink("X", $"Delete/{recipe.ID}", "Recipes", null, new { @class = "btn btn-primary" })
                    </td>

                </tr>
            }
        </tbody>
    </table>*@

    <div class="recipes-list-container">

        @foreach (var recipe in Model.recipes)
        {
        <div class="recipe-in-container">


            @Html.ActionLink(recipe.Title, "Edit", "Recipes", new { id = recipe.ID }, null)
            <h4>Kategoria: @recipe.RecipeType.Name</h4>
            <div class="recipe-buttons">
                @Html.ActionLink("Przepis", $"Details/{recipe.ID}", "Recipes", null, new { @class = "btn btn-primary" })
                @Html.ActionLink("Usuń", $"Delete/{recipe.ID}", "Recipes", null, new { @class = "btn btn-primary" })

            </div>

        </div>
        }


    </div>




    <p>
        @if (User.Identity.IsAuthenticated)
        {

            @Html.ActionLink("Dodaj przepis", "New", "Recipes", null, new { @class = "btn btn-primary" })
        }
    </p>
}

KsiazkaOnline/Views/Recipes/New.cshtml
@model KsiazkaOnline.ViewModels.NewRecipeViewModel
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Title</h2>
@Html.ValidationSummary()
@using (Html.BeginForm("Save", "Recipes"))
{
    <div class="form-group">
        <label>Tytuł Dania</label>
        @Html.TextBoxFor(r => r.recipe.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(r => r.recipe.Title)

    </div>
    <div class="form-group">
        <label>Opis przygotowania dania</label>
        @Html.TextBoxFor(r => r.recipe.Description, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(r => r.recipe.RecipeTypeId)
        @Html.DropDownListFor(r => r.recipe.RecipeTypeId, new SelectList(@Model.types, "Id", "Name"), "Wybierz rodzaj", new { @class = "form-control" })
        @Html.ValidationMessageFor(r => r.recipe.RecipeTypeId)

    </div>

    @Html.HiddenFor(r => r.recipe.ID)

    <button type="submit" , class="btn btn-primary">Dodaj</button>
}